services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: rpm24/swe_project_2:frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: rpm24/swe_project_2:backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=course_db
    depends_on:
      - database
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: rpm24/swe_project_2:database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=course_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: